# -*- coding: utf-8 -*-
"""DolFin - User C Home Loan Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nNBcb_AiDPlHUFNoxF_3aPg8jRgFG4r_
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Set random seed for reproducibility
np.random.seed(0)

# Set User ID
user_id = 7

# Define loan parameters
initial_balance = -np.random.uniform(300000, 750000)
interest_rate = 0.0611
loan_term_months = 30 * 12

# Calculate monthly interest rate
monthly_interest_rate = interest_rate / 12

# Calculate monthly payment using provided methodology
monthly_payment = (initial_balance * monthly_interest_rate) / (1 - (1 + monthly_interest_rate) ** -loan_term_months)

# Generate dates
dates = pd.date_range(start='2022-01-01', end='2024-01-01', freq='MS')

# Convert dates to datetime format
dates = pd.to_datetime(dates)

# Initialise lists to store data
transaction_details = []
amounts = []
totals = []

# Initialise balance
balance = initial_balance

# Generate transaction details, amounts, and totals
for date in dates:
    # Interest Charged
    transaction_details.append('Interest charged')
    interest_charged = balance * monthly_interest_rate
    amounts.append(interest_charged)
    balance += interest_charged
    totals.append(balance)

    # Repayment/Payment (Principal payment)
    transaction_details.append('Repayment/Payment')
    principal_payment = monthly_payment
    amounts.append(principal_payment)
    balance -= principal_payment
    totals.append(balance)

# Create DataFrame
data = {
    'Date': dates.repeat(2),
    'Transaction Details': transaction_details,
    'Amount': amounts,
    'Total': totals
}
df = pd.DataFrame(data)

# Convert Repayment/Payment amounts to positive
df.loc[df['Transaction Details'] == 'Repayment/Payment', 'Amount'] = df.loc[df['Transaction Details'] == 'Repayment/Payment', 'Amount'].abs()

# Format Amount and Total columns
df['Amount'] = df['Amount'].map('${:,.2f}'.format)
df['Total'] = df['Total'].map('${:,.2f}'.format)

df